sudo: required
addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

install:  echo "skip bundle install"

services:
  - docker

env:
  matrix:
  - CHEF_VERSION=latest LANGUAGE=ruby OS=centos-7
  - CHEF_VERSION=latest LANGUAGE=rust OS=centos-7
  
language: ruby
before_script:
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
script:
- /opt/chefdk/bin/chef --version
