sudo: required
services:
  - docker
language: ruby
before_install:
- wget https://packages.chef.io/files/stable/chefdk/3.0.36/el/7/chefdk-3.0.36-1.el7.x86_64.rpm 
install:
- sudo rpm -ivh chefdk-3.0.36-1.el7.x86_64.rpm
- /opt/chefdk/bin/chef gem install kitchen-docker rake foodcritic test-kitchen kitchen-docker kitchen-inspec berkshelf
script:
- /opt/chefdk/bin/chef exec foodcritic .
- /opt/chefdk/bin/chef exec kitchen create
- /opt/chefdk/bin/chef exec kitchen converge
- /opt/chefdk/bin/chef exec kitchen destroy
